### ISSUE TITLE
torch.jit.trace() error: Tracer cannot infer type of BoxList

### ISSUE THREAD

**Issue by ulyssesxxxi** [pytorch/tvm#74]
Hi,

I'm trying to run maskrcnn_benchmark on TVM using pytorch/tvm (specifically e2e_mask_rcnn_X-152-32x8d-FPN-IN5k_1.44x_caffe2). During torch.jit.trace() invocation, it throws the following error: "Tracer cannot infer type of BoxList". I'm aware that BoxList is an specific class of maskrcnn_benchmark, and I assume that I'd need to implement custom ops for symbolic_mult_label_nms() and symbolic_roi_align() (where I think BoxLists are used, although I'm not 100% sure). Could you please provide me further directions on this, or tell me whether there is any other approach to make the Tracer process BoxList objects?

Thanks in advance.

**Comment by bwasti** [comment]
Hey @ulyssesxxxi, thanks for bringing this to our attention!

This bug seems to be related to the more general PyTorch JIT effort.  If you wouldn't mind, please use this link to file a bug report there: https://github.com/pytorch/pytorch/issues/new/choose
